const DESKTOPWITH: number = 1200;
const TABLETWITH: number = 970;

const MAINDESKTOPWIDTH: number = 1220;
const MAINTABLETWITH: number = 950;

enum SHIFT {
  MAX = 297,
  MIN = 323,
  HEIGTH =124,
} 

export { DESKTOPWITH, TABLETWITH, MAINDESKTOPWIDTH, MAINTABLETWITH, SHIFT };